name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure OCI Token
      uses: bytesbay/oci-cli-action@v1.0.1
      with:
        user: ${{ secrets.OCI_USER }}
        fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
        tenancy: ${{ secrets.OCI_TENANCY }}
        region: ${{ secrets.OCI_REGION }}
        api_key: ${{ secrets.OCI_API_KEY }}
        oci-auth-token: ${{ secrets.OCI_TOKEN }}
    - name: List Object storage
      run: oci os object list --bucket-name kyudong
