name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
      
    - name: Install oci-cli
      uses: bytesbay/oci-cli-action@v1.0.1
      with:
        user: "${{ secrets.OCI_USER }}"
        fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
        tenancy: "${{ secrets.OCI_TENANCY }}"
        region: "${{ secrets.OCI_REGION }}"
        api_key: "${{ secrets.OCI_API_KEY }}"
        verbose: true
    - run: cat ~/.oci/config  
    - run: oci -v
    - name: List Object storage
      run: oci os object list --bucket-name kyudong
